apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/instance: ingress-nginx-second
    app.kubernetes.io/name: ingress-nginx-second
  name: ingress-nginx-second
---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx-second
    app.kubernetes.io/name: ingress-nginx-second
    app.kubernetes.io/part-of: ingress-nginx-second
    app.kubernetes.io/version: 1.11.2
  name: ingress-nginx-second
  namespace: ingress-nginx-second
---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: admission-webhook
    app.kubernetes.io/instance: ingress-nginx-second
    app.kubernetes.io/name: ingress-nginx-second
    app.kubernetes.io/part-of: ingress-nginx-second
    app.kubernetes.io/version: 1.11.2
  name: ingress-nginx-second-admission
  namespace: ingress-nginx-second
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx-second
    app.kubernetes.io/name: ingress-nginx-second
    app.kubernetes.io/part-of: ingress-nginx-second
    app.kubernetes.io/version: 1.11.2
  name: ingress-nginx-second
  namespace: ingress-nginx-second
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - secrets
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses/status
  verbs:
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingressclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resourceNames:
  - ingress-nginx-second-leader
  resources:
  - leases
  verbs:
  - get
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - list
  - watch
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: admission-webhook
    app.kubernetes.io/instance: ingress-nginx-second
    app.kubernetes.io/name: ingress-nginx-second
    app.kubernetes.io/part-of: ingress-nginx-second
    app.kubernetes.io/version: 1.11.2
  name: ingress-nginx-second-admission
  namespace: ingress-nginx-second
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: ingress-nginx-second
    app.kubernetes.io/name: ingress-nginx-second
    app.kubernetes.io/part-of: ingress-nginx-second
    app.kubernetes.io/version: 1.11.2
  name: ingress-nginx-second
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - nodes
  - pods
  - secrets
  - namespaces
  verbs:
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses/status
  verbs:
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingressclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - list
  - watch
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: admission-webhook
    app.kubernetes.io/instance: ingress-nginx-second
    app.kubernetes.io/name: ingress-nginx-second
    app.kubernetes.io/part-of: ingress-nginx-second
    app.kubernetes.io/version: 1.11.2
  name: ingress-nginx-second-admission
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - get
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx-second
    app.kubernetes.io/name: ingress-nginx-second
    app.kubernetes.io/part-of: ingress-nginx-second
    app.kubernetes.io/version: 1.11.2
  name: ingress-nginx-second
  namespace: ingress-nginx-second
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ingress-nginx-second
subjects:
- kind: ServiceAccount
  name: ingress-nginx-second
  namespace: ingress-nginx-second
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: admission-webhook
    app.kubernetes.io/instance: ingress-nginx-second
    app.kubernetes.io/name: ingress-nginx-second
    app.kubernetes.io/part-of: ingress-nginx-second
    app.kubernetes.io/version: 1.11.2
  name: ingress-nginx-second-admission
  namespace: ingress-nginx-second
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ingress-nginx-second-admission
subjects:
- kind: ServiceAccount
  name: ingress-nginx-second-admission
  namespace: ingress-nginx-second
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: ingress-nginx-second
    app.kubernetes.io/name: ingress-nginx-second
    app.kubernetes.io/part-of: ingress-nginx-second
    app.kubernetes.io/version: 1.11.2
  name: ingress-nginx-second
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingress-nginx-second
subjects:
- kind: ServiceAccount
  name: ingress-nginx-second
  namespace: ingress-nginx-second
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: admission-webhook
    app.kubernetes.io/instance: ingress-nginx-second
    app.kubernetes.io/name: ingress-nginx-second
    app.kubernetes.io/part-of: ingress-nginx-second
    app.kubernetes.io/version: 1.11.2
  name: ingress-nginx-second-admission
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingress-nginx-second-admission
subjects:
- kind: ServiceAccount
  name: ingress-nginx-second-admission
  namespace: ingress-nginx-second
---
apiVersion: v1
data:
  allow-snippet-annotations: "false"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx-second
    app.kubernetes.io/name: ingress-nginx-second
    app.kubernetes.io/part-of: ingress-nginx-second
    app.kubernetes.io/version: 1.11.2
  name: ingress-nginx-second-controller
  namespace: ingress-nginx-second
---
apiVersion: v1
kind: Service
metadata:
  annotations:
   #kubectl.kubernetes.io/last-applied-configuration: |
      #{"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"controller","app.kubernetes.io/instance":"ingress-nginx-second","app.kubernetes.io/name":"ingress-nginx-second","app.kubernetes.io/part-of":"ingress-nginx-second","app.kubernetes.io/version":"1.11.2"},"name":"ingress-nginx-second-controller","namespace":"ingress-nginx-second"},"spec":{"ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"appProtocol":"http","name":"http","port":80,"protocol":"TCP","targetPort":"http"},{"appProtocol":"https","name":"https","port":443,"protocol":"TCP","targetPort":"https"}],"selector":{"app.kubernetes.io/component":"controller","app.kubernetes.io/instance":"ingress-nginx-second","app.kubernetes.io/name":"ingress-nginx-second"},"type":"NodePort"}}
  creationTimestamp: "2024-10-15T09:13:26Z"
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx-second
    app.kubernetes.io/name: ingress-nginx-second
    app.kubernetes.io/part-of: ingress-nginx-second
    app.kubernetes.io/version: 1.11.2
  name: ingress-nginx-second-controller
  namespace: ingress-nginx-second
  #resourceVersion: "10881118"
  #uid: 6ad5757b-e567-44e2-84d3-d0e614f3271b
spec:
  clusterIP: 10.43.157.231
  clusterIPs:
  - 10.43.157.231
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - appProtocol: http
    name: http
    nodePort: 31194
    port: 80
    protocol: TCP
    targetPort: http
  - appProtocol: https
    name: https
    nodePort: 31634
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx-second
    app.kubernetes.io/name: ingress-nginx-second
  sessionAffinity: None
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx-second
    app.kubernetes.io/name: ingress-nginx-second
    app.kubernetes.io/part-of: ingress-nginx-second
    app.kubernetes.io/version: 1.11.2
  name: ingress-nginx-second-controller-admission
  namespace: ingress-nginx-second
spec:
  ports:
  - appProtocol: https
    name: https-webhook
    port: 443
    targetPort: webhook
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx-second
    app.kubernetes.io/name: ingress-nginx-second
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx-second
    app.kubernetes.io/name: ingress-nginx-second
    app.kubernetes.io/part-of: ingress-nginx-second
    app.kubernetes.io/version: 1.11.2
  name: ingress-nginx-second-controller
  namespace: ingress-nginx-second
spec:
  minReadySeconds: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: ingress-nginx-second
      app.kubernetes.io/name: ingress-nginx-second
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/instance: ingress-nginx-second
        app.kubernetes.io/name: ingress-nginx-second
        app.kubernetes.io/part-of: ingress-nginx-second
        app.kubernetes.io/version: 1.11.2
    spec:
      containers:
      - args:
        - /nginx-ingress-controller
        - --election-id=ingress-nginx-second-leader
        - --controller-class=k8s.io/ingress-nginx
        - --ingress-class=nginx-second
        - --configmap=$(POD_NAMESPACE)/ingress-nginx-second-controller
        - --validating-webhook=:8443
        - --validating-webhook-certificate=/usr/local/certificates/cert
        - --validating-webhook-key=/usr/local/certificates/key
        - --enable-metrics=false
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: LD_PRELOAD
          value: /usr/local/lib/libmimalloc.so
        image: registry.k8s.io/ingress-nginx/controller:v1.11.2@sha256:d5f8217feeac4887cb1ed21f27c2674e58be06bd8f5184cacea2a69abaf78dce
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /wait-shutdown
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: controller
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        - containerPort: 8443
          name: webhook
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 90Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 101
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /usr/local/certificates/
          name: webhook-cert
          readOnly: true
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: ingress-nginx-second
      terminationGracePeriodSeconds: 300
      volumes:
      - name: webhook-cert
        secret:
          secretName: ingress-nginx-second-admission
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/component: admission-webhook
    app.kubernetes.io/instance: ingress-nginx-second
    app.kubernetes.io/name: ingress-nginx-second
    app.kubernetes.io/part-of: ingress-nginx-second
    app.kubernetes.io/version: 1.11.2
  name: ingress-nginx-second-admission-create
  namespace: ingress-nginx-second
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/component: admission-webhook
        app.kubernetes.io/instance: ingress-nginx-second
        app.kubernetes.io/name: ingress-nginx-second
        app.kubernetes.io/part-of: ingress-nginx-second
        app.kubernetes.io/version: 1.11.2
      name: ingress-nginx-second-admission-create
    spec:
      containers:
      - args:
        - create
        - --host=ingress-nginx-second-controller-admission,ingress-nginx-second-controller-admission.$(POD_NAMESPACE).svc
        - --namespace=$(POD_NAMESPACE)
        - --secret-name=ingress-nginx-second-admission
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.4.3@sha256:a320a50cc91bd15fd2d6fa6de58bd98c1bd64b9a6f926ce23a600d87043455a3
        imagePullPolicy: IfNotPresent
        name: create
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65532
          seccompProfile:
            type: RuntimeDefault
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: OnFailure
      serviceAccountName: ingress-nginx-second-admission
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/component: admission-webhook
    app.kubernetes.io/instance: ingress-nginx-second
    app.kubernetes.io/name: ingress-nginx-second
    app.kubernetes.io/part-of: ingress-nginx-second
    app.kubernetes.io/version: 1.11.2
  name: ingress-nginx-second-admission-patch
  namespace: ingress-nginx-second
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/component: admission-webhook
        app.kubernetes.io/instance: ingress-nginx-second
        app.kubernetes.io/name: ingress-nginx-second
        app.kubernetes.io/part-of: ingress-nginx-second
        app.kubernetes.io/version: 1.11.2
      name: ingress-nginx-second-admission-patch
    spec:
      containers:
      - args:
        - patch
        - --webhook-name=ingress-nginx-second-admission
        - --namespace=$(POD_NAMESPACE)
        - --patch-mutating=false
        - --secret-name=ingress-nginx-second-admission
        - --patch-failure-policy=Fail
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.4.3@sha256:a320a50cc91bd15fd2d6fa6de58bd98c1bd64b9a6f926ce23a600d87043455a3
        imagePullPolicy: IfNotPresent
        name: patch
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65532
          seccompProfile:
            type: RuntimeDefault
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: OnFailure
      serviceAccountName: ingress-nginx-second-admission
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx-second
    app.kubernetes.io/name: ingress-nginx-second
    app.kubernetes.io/part-of: ingress-nginx-second
    app.kubernetes.io/version: 1.11.2
  name: nginx-second
spec:
  controller: k8s.io/ingress-nginx
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    app.kubernetes.io/component: admission-webhook
    app.kubernetes.io/instance: ingress-nginx-second
    app.kubernetes.io/name: ingress-nginx-second
    app.kubernetes.io/part-of: ingress-nginx-second
    app.kubernetes.io/version: 1.11.2
  name: ingress-nginx-second-admission
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: ingress-nginx-second-controller-admission
      namespace: ingress-nginx-second
      path: /networking/v1/ingresses
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validate.nginx.ingress.kubernetes.io
  rules:
  - apiGroups:
    - networking.k8s.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ingresses
  sideEffects: None
